# Generated by Django 6.0.4 on 2026-09-15 05:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0006_coinsetting_academy_notnull'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cointransaction',
            index=models.Index(fields=['student', 'type', '-created_at'], name='coins_coint_student_592007_idx'),
        ),
    ]
