# Generated by Django 6.0.4 on 2026-09-15 05:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0022_lesson_ended_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'present'], name='groups_atte_student_807409_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['lesson', 'present'], name='groups_atte_lesson__b4672f_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['teacher', 'is_graduated'], name='groups_grou_teacher_f8eb49_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['teacher', 'is_individual', 'is_graduated'], name='groups_grou_teacher_506d8d_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['group', 'joined_at'], name='groups_grou_group_i_5429ab_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['student', 'joined_at'], name='groups_grou_student_bf0d94_idx'),
        ),
        migrations.AddIndex(
            model_name='homeworksubmission',
            index=models.Index(fields=['student', 'submitted_at'], name='groups_home_student_de167d_idx'),
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['student', 'updated_at'], name='groups_jour_student_7dd8bb_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['group', 'date'], name='groups_less_group_i_50172d_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['group', '-created_at'], name='groups_less_group_i_1541ed_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['student'], name='groups_scor_student_e268a9_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['lesson'], name='groups_scor_lesson__f12d43_idx'),
        ),
    ]
