# Generated by Django 6.0.4 on 2026-09-15 05:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0008_academy_stamp'),
        ('groups', '0023_attendance_groups_atte_student_807409_idx_and_more'),
        ('payments', '0003_enrollment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['group', 'started_at', 'ended_at'], name='payments_en_group_i_0f7e24_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['student', 'group', 'paid_at'], name='payments_pa_student_d33100_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['group', 'paid_at'], name='payments_pa_group_i_647a02_idx'),
        ),
        migrations.AddIndex(
            model_name='studenttuition',
            index=models.Index(fields=['group', 'student'], name='payments_st_group_i_041ea4_idx'),
        ),
        migrations.AddIndex(
            model_name='tuitioncategory',
            index=models.Index(fields=['academy', 'name'], name='payments_tu_academy_2d4b93_idx'),
        ),
        migrations.AddIndex(
            model_name='tuitiontemplate',
            index=models.Index(fields=['academy', 'category', 'name'], name='payments_tu_academy_dcff79_idx'),
        ),
    ]
