# Generated by Django 6.0.4 on 2026-09-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0008_academy_stamp'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0016_alter_notification_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='users_notif_user_id_f3f50a_idx'),
        ),
        migrations.AddIndex(
            model_name='parentstudent',
            index=models.Index(fields=['student', 'parent'], name='users_paren_student_10a4d3_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['academy', 'role', 'is_active'], name='users_user_academy_0ca708_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_seen'], name='users_user_last_se_f36183_idx'),
        ),
    ]
